apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-serviceaccount.yaml
  - vault-auth-sa.yaml
  - vault-clusterrole.yaml
  - vault-clusterrolebinding.yaml
  - vault-token-creator-binding.yaml
  - k8s-full-secrets-abilities.yaml
