
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: idrac-secret
  namespace: idrac
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: idrac/idrac-secret
      metadataPolicy: None
      property: IDRAC_PASSWORD
    secretKey: IDRAC_PASSWORD
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: idrac/idrac-secret
      metadataPolicy: None
      property: API_SERVER
    secretKey: API_SERVER
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: idrac/idrac-secret
      metadataPolicy: None
      property: IDRAC_USER
    secretKey: IDRAC_USER
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: idrac/idrac-secret
      metadataPolicy: None
      property: IDRAC_HOST
    secretKey: IDRAC_HOST
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: idrac/idrac-secret
      metadataPolicy: None
      property: OC_USER
    secretKey: OC_USER
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: idrac/idrac-secret
      metadataPolicy: None
      property: OC_PASSWORD
    secretKey: OC_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-sno-mini
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: idrac-secret