apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd.yaml
  - principal-cert.yaml
  - repo-external-secret.yaml
  - appset-in-any-namespace-clusterrole.yaml
  - agent-principal-rbac.yaml
  - acm-policy-rolebinding.yaml
