apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-ocp-homelab
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: '5'
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: repo-ocp-homelab
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: openshift-gitops/repo-ocp-homelab
        property: password
    - secretKey: type
      remoteRef:
        key: openshift-gitops/repo-ocp-homelab
        property: type
    - secretKey: url
      remoteRef:
        key: openshift-gitops/repo-ocp-homelab
        property: url
    - secretKey: username
      remoteRef:
        key: openshift-gitops/repo-ocp-homelab
        property: username
