apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sno-mini-agent-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd-agent-sno-mini
    server: https://kubernetes.default.svc
  project: argocd-agent-sno-mini
  source:
    repoURL: https://github.com/shane-snyder/ocp-homelab.git
    targetRevision: HEAD
    path: clusters/sno-mini
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/project
        - /spec/destination/server
        - /spec/destination/name
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
