apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/tracking-id: quay-sno-mini:external-secrets.io/ExternalSecret:quay-enterprise/config-bundle-secret
  name: config-bundle-secret
  namespace: quay-enterprise
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: quay/config-bundle-secret
      metadataPolicy: None
      property: config.yaml
    secretKey: config.yaml
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-sno-mini
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: config-bundle-secret
