apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../../../components/quay
  - 003-config-bundle-secret-external-secret.yaml
  - 004-quayregistry.yaml
  - 005-minio-nodeport.yaml
