apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/cert-manager-configuration

patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: api-cert
      namespace: openshift-config
    path: patch-api.json
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: ingress-cert
      namespace: openshift-ingress
    path: patch-ingress.json
