apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - default: false
        deviceSelector:
          paths:
            - /dev/disk/by-id/wwn-0x61866da096299f002ea5c0192fbc49f2
        fstype: xfs
        name: minio
        thinPoolConfig:
          name: thin-pool-2
          overprovisionRatio: 10
          sizePercent: 90
      - default: true
        deviceSelector:
          paths:
            - /dev/disk/by-id/wwn-0x61866da096299f002ea5bf4c238028e7
        fstype: xfs
        name: dell
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
