apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - ../../../../components/lvms-operator

patches:
  - path: channel-patch.yaml
    target:
      group: operators.coreos.com
      kind: Subscription
      name: lvms-operator
      namespace: openshift-storage
      version: v1alpha1
  - path: device-classes.yaml
