apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-tempo-ossm3-configuration
  namespace: opentelemetry
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: minio-tempo-ossm3-configuration
    creationPolicy: Owner
    template:
      data:
        config.env: |
          export MINIO_ROOT_USER={{ .rootUser }}
          export MINIO_ROOT_PASSWORD={{ .rootPassword }}
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio/tempo-ossm3
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: minio/tempo-ossm3
        property: rootPassword
