apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '7'
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: argocd-notifications-secret
    app.kubernetes.io/part-of: argocd
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
  data:
    - secretKey: slack-token
      remoteRef:
        key: openshift-gitops/argocd-notifications-secret
        property: slack-token