apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../.helm-charts

helmCharts:
  - name: argocd-app-of-app
    releaseName: sno-mini-agent-apps
    namespace: argocd-agent-sno-mini
    valuesFile: values.yaml
