apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhel10-dnf-check-cloudinit
  namespace: rhel10-vm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: rhel10-dnf-check-cloudinit
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        userdata: |
          #cloud-config
          user: cloud-user
          password: {{ .password }}
          chpasswd:
            expire: false
  data:
    - secretKey: password
      remoteRef:
        key: rhel10-vm/rhel10-dnf-check-cloudinit
        property: password
