apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redfish-secret
  namespace: openshift-power-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: redfish-secret
    creationPolicy: Owner
  data:
    - secretKey: redfish.csv
      remoteRef:
        key: openshift-power-monitoring/redfish-secret
        property: redfish.csv