apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno-mini
    kind: ClusterSecretStore
  target:
    name: tailscale-oauth
    creationPolicy: Owner
  data:
    - secretKey: clientId
      remoteRef:
        key: tailscale/tailscale-oauth
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: tailscale/tailscale-oauth
        property: clientSecret
