{{- if and .Values.route .Values.route.s3 .Values.route.s3.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "garage.fullname" . }}-s3
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.s3.host }}
  to:
    kind: Service
    name: {{ include "garage.fullname" . }}
    weight: 100
  port:
    targetPort: s3-api
  tls:
    termination: {{ .Values.route.s3.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
