apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: grafana-lab
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: grafana-lab
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    app.kubernetes.io/name: loki
  ports:
    # /otlp/v1/logs      <- OTel collectors
    # /loki/api/v1/*     <- Grafana queries
    - { name: http-metrics, port: 3100, targetPort: http-metrics }
    - { name: grpc, port: 9096, targetPort: grpc }
    - { name: du-metrics, port: 9110, targetPort: du-metrics }
