apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

resources:
  - ../../../../components/acs-secured-clusters
  - sno-mini-Operator-secrets-cluster-init-bundle.yaml
