apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: managed-clusters
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Applications deployed to managed clusters via agent mode
  sourceRepos:
    - https://github.com/shane-snyder/ocp-homelab.git
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
