apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretStoreRef:
    name: vault-sno-mini
    kind: ClusterSecretStore
  target:
    name: htpass-secret
    creationPolicy: Owner
  data:
    - secretKey: htpasswd
      remoteRef:
        key: openshift-config/htpass-secret
        property: htpasswd