apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-gitops-catalog
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: '5'
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: repo-gitops-catalog
    creationPolicy: Owner
  data:
    - secretKey: project
      remoteRef:
        key: openshift-gitops/repo-gitops-catalog
        property: project
    - secretKey: type
      remoteRef:
        key: openshift-gitops/repo-gitops-catalog
        property: type
    - secretKey: url
      remoteRef:
        key: openshift-gitops/repo-gitops-catalog
        property: url