apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-sno
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: '5'
  labels:
    argocd.argoproj.io/secret-type: repository
    argocd.argoproj.io/application: gitops
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: repo-sno
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: openshift-gitops/repo-sno
        property: password
    - secretKey: project
      remoteRef:
        key: openshift-gitops/repo-sno
        property: project
    - secretKey: type
      remoteRef:
        key: openshift-gitops/repo-sno
        property: type
    - secretKey: url
      remoteRef:
        key: openshift-gitops/repo-sno
        property: url
    - secretKey: username
      remoteRef:
        key: openshift-gitops/repo-sno
        property: username