apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-api.sno-mini.shanehomelab.com-376892625
  namespace: openshift-gitops
  annotations:
    managed-by: argocd.argoproj.io
    argocd.argoproj.io/sync-wave: '6'
  labels:
    argocd.argoproj.io/secret-type: cluster
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: cluster-api.sno-mini.shanehomelab.com-376892625
    creationPolicy: Owner
  data:
    - secretKey: config
      remoteRef:
        key: openshift-gitops/cluster-api.sno-mini.shanehomelab.com-376892625
        property: config
    - secretKey: name
      remoteRef:
        key: openshift-gitops/cluster-api.sno-mini.shanehomelab.com-376892625
        property: name
    - secretKey: server
      remoteRef:
        key: openshift-gitops/cluster-api.sno-mini.shanehomelab.com-376892625
        property: server