---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - 001-namespace.yaml
  - 002-lvms-subcription.yaml
  - 002-operator-group.yaml
  - 003-lvmcluster.yaml
