apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-sno
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
          namespace: external-secrets
      path: sno/
      server: https://vault.apps.sno-mini.shanehomelab.com
      version: v2