apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: multiclusterhub-operator-pull-secret
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: open-cluster-management-observability/multiclusterhub-operator-pull-secret
        property: .dockerconfigjson