apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: thanos-object-storage
    creationPolicy: Owner
  data:
    - secretKey: thanos.yaml
      remoteRef:
        key: open-cluster-management-observability/thanos-object-storage
        property: thanos.yaml