apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-config
  namespace: open-cluster-management-observability
  annotations:
    skip-creation-if-exist: "true"
    argocd.argoproj.io/sync-wave: "6"
  labels:
    cluster.open-cluster-management.io/backup: ""
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: alertmanager-config
    creationPolicy: Merge
  data:
    - secretKey: alertmanager.yaml
      remoteRef:
        key: open-cluster-management-observability/alertmanager-config
        property: alertmanager.yaml