---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-multiclusterhub-operator-external-pull-secret.yaml
  - 03-thanos-external-secret.yaml
  - 04-multiclusterobservability.yaml
  - 05-observability-metrics-custom-allowlist.yaml
  - 06-alertmanager-external-secret.yaml
  - 07-operators.yaml

