apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-metrics-custom-allowlist
  namespace: quay-enterprise
data:
  uwl_metrics_list.yaml: |
    names:
      - bearer_token_decoded_created
      - bearer_token_decoded_total
      - go_gc_duration_seconds
      - go_goroutines
      - go_info
      - go_memstats_alloc_bytes
      - go_memstats_alloc_bytes_total
      - go_memstats_buck_hash_sys_bytes
      - go_memstats_frees_total
      - go_memstats_gc_sys_bytes
      - go_memstats_heap_alloc_bytes
      - go_memstats_heap_idle_bytes
      - go_memstats_heap_inuse_bytes
      - go_memstats_heap_objects
      - go_memstats_heap_released_bytes
      - go_memstats_heap_sys_bytes
      - go_memstats_last_gc_time_seconds
      - go_memstats_lookups_total
      - go_memstats_mallocs_total
      - go_memstats_mcache_inuse_bytes
      - go_memstats_mcache_sys_bytes
      - go_memstats_mspan_inuse_bytes
      - go_memstats_mspan_sys_bytes
      - go_memstats_next_gc_bytes
      - go_memstats_other_sys_bytes
      - go_memstats_stack_inuse_bytes
      - go_memstats_stack_sys_bytes
      - go_memstats_sys_bytes
      - go_threads
      - greenlet_duration_seconds
      - greenlet_duration_seconds_created
      - greenlet_switch_created
      - greenlet_switch_total
      - greenlet_throw_created
      - greenlet_throw_total
      - process_cpu_seconds_total
      - process_max_fds
      - process_open_fds
      - process_resident_memory_bytes
      - process_start_time_seconds
      - process_virtual_memory_bytes
      - process_virtual_memory_max_bytes
      - push_failure_time_seconds
      - push_time_seconds
      - pushgateway_build_info
      - pushgateway_http_push_duration_seconds
      - pushgateway_http_push_size_bytes
      - pushgateway_http_requests_total
      - python_gc_collections_total
      - python_gc_objects_collected_total
      - python_gc_objects_uncollectable_total
      - python_info
      - quay_authentication_attempts_created
      - quay_authentication_attempts_total
      - quay_db_close_calls_created
      - quay_db_close_calls_total
      - quay_db_connect_calls_created
      - quay_db_connect_calls_total
      - quay_db_pooled_connections_available
      - quay_db_pooled_connections_in_use
      - quay_gc_iterations_created
      - quay_gc_iterations_total
      - quay_gc_namespaces_purged_created
      - quay_gc_namespaces_purged_total
      - quay_gc_repos_purged_created
      - quay_gc_repos_purged_total
      - quay_gc_storage_blobs_deleted_created
      - quay_gc_storage_blobs_deleted_total
      - quay_instance_key_renewal_self_created
      - quay_instance_key_renewal_self_total
      - quay_model_cache_created
      - quay_model_cache_total
      - quay_multipart_uploads_completed_created
      - quay_multipart_uploads_completed_total
      - quay_multipart_uploads_started_created
      - quay_multipart_uploads_started_total
      - quay_org_rows
      - quay_queue_item_deletes_created
      - quay_queue_item_deletes_total
      - quay_queue_item_gets_created
      - quay_queue_item_gets_total
      - quay_queue_item_puts_created
      - quay_queue_item_puts_total
      - quay_queue_items_available
      - quay_queue_items_available_unlocked
      - quay_queue_items_locked
      - quay_registry_image_pulled_estimated_bytes_created
      - quay_registry_image_pulled_estimated_bytes_total
      - quay_registry_image_pushed_bytes_created
      - quay_registry_image_pushed_bytes_total
      - quay_registry_image_pushes_created
      - quay_registry_image_pushes_total
      - quay_repository_rows
      - quay_request_duration_seconds
      - quay_request_duration_seconds_created
      - quay_robot_rows
      - quay_secscan_index_layer_size_bytes
      - quay_secscan_index_layer_size_bytes_created
      - quay_secscan_result_duration_seconds
      - quay_secscan_result_duration_seconds_created
      - quay_user_rows
      - kubevirt_vmi_phase_count
      - kubevirt_vmi_storage_read_traffic_bytes_total
      - kubevirt_allocatable_nodes_count
      - kubevirt_vmi_memory_available_bytes
      - kubevirt_vmi_memory_usable_bytes
      - kubevirt_vmi_storage_iops_read_total
      - kubevirt_vmi_storage_iops_write_total
      - kubevirt_vmi_storage_read_traffic_bytes_total
      - kubevirt_vmi_network_receive_bytes_total
      - kubevirt_vmi_network_transmit_bytes_total
      - kubevirt_vmi_phase_transition_time_from_creation_seconds_bucket
      - kube_subscription_labels
