{{- range .Values.tenant.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: {{ .name | trimSuffix "-user-creds" }}
  CONSOLE_SECRET_KEY: {{ .name | trimSuffix "-user-creds" }}{{ .name | trimSuffix "-user-creds" }}123
---
{{- end }}