apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-sno-mini
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: openshift-sno-mini
          role: eso-role
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      path: sno-mini/
      server: https://vault.apps.sno-mini.shanehomelab.com
      version: v2