---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - multiclusterhub.yaml
  - multiclusterengine.yaml
  - subscription-admin.yaml
  - metal-provisioning.yaml
  - agent-service-configuration.yaml
