apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ansible-galaxy-object-storage
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: ansible-galaxy-object-storage
    creationPolicy: Owner
    template:
      data:
        s3_url: "http://garage.garage.svc:3900"
        s3_access_key: "{{ .accessKey }}"
        s3_secret_key: "{{ .secretKey }}"
        s3_bucket_name: "ansible-observability"
        s3_region: "us-east-1"
  data:
    - secretKey: accessKey
      remoteRef:
        key: garage/ansible
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: garage/ansible
        property: secretKey
