apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-quay-credentials
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: garage-quay-credentials
    creationPolicy: Owner
  data:
    - secretKey: accessKey
      remoteRef:
        key: garage/quay
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: garage/quay
        property: secretKey
