apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: cloud-credentials
    creationPolicy: Merge
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .accessKey }}
          aws_secret_access_key={{ .secretKey }}
  data:
    - secretKey: accessKey
      remoteRef:
        key: garage/oadp
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: garage/oadp
        property: secretKey
