apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ossm3-storage-secret
  namespace: opentelemetry
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: ossm3-storage-secret
    creationPolicy: Owner
    template:
      data:
        endpoint: "http://garage.garage.svc:3900"
        bucket: "tempo-ossm3"
        access_key_id: "{{ .accessKey }}"
        access_key_secret: "{{ .secretKey }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: garage/tempo
        property: accessKey
    - secretKey: secretKey
      remoteRef:
        key: garage/tempo
        property: secretKey
