apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secret-ossm3-storage.yaml
  - external-secret-oadp-cloud-credentials.yaml
  - external-secret-quay-storage.yaml
  - external-secret-ansible-storage.yaml
