apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-agent

resources:
  - ../../../../components/argocd-agent-spoke
  - argocd-agent-ca.yaml
  - argocd-agent-client-tls.yaml
  - repo-ocp-homelab.yaml
