apiVersion: v1
kind: Secret
metadata:
  name: repo-ocp-homelab
  namespace: argocd-agent
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  password: '{{hub (fromSecret "argocd" "repo-ocp-homelab" "password") hub}}'
  type: '{{hub (fromSecret "argocd" "repo-ocp-homelab" "type") hub}}'
  url: '{{hub (fromSecret "argocd" "repo-ocp-homelab" "url") hub}}'
  username: '{{hub (fromSecret "argocd" "repo-ocp-homelab" "username") hub}}'
