apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: local-cluster
spec:
  clusterName: local-cluster
  customize:
    envVars:
      # Required on Sensor as well as Central for global pull-secret registry integrations.
      - name: ROX_AUTOGENERATE_GLOBAL_PULLSEC_REGISTRIES
        value: 'true'
  monitoring:
    openshift:
      enabled: true
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
