apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ""
    argocd.argoproj.io/sync-wave: '1'
  name: openshift-cluster-observability-operator-v6c6z
  namespace: openshift-cluster-observability-operator
spec:
  upgradeStrategy: Default
