apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-ocp-apps
  namespace: argocd-agent-sno-mini
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-sno-mini
  target:
    name: repo-ocp-apps
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: password
      remoteRef:
        key: argocd-agent-sno-mini/repo-ocp-apps
        property: password
    - secretKey: type
      remoteRef:
        key: argocd-agent-sno-mini/repo-ocp-apps
        property: type
    - secretKey: url
      remoteRef:
        key: argocd-agent-sno-mini/repo-ocp-apps
        property: url
    - secretKey: username
      remoteRef:
        key: argocd-agent-sno-mini/repo-ocp-apps
        property: username
