apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-dell
