apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui-secret
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: vault-sno
    kind: ClusterSecretStore
  target:
    name: open-webui-secret
    creationPolicy: Owner
  data:
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: ollama/open-webui-secret
        property: WEBUI_SECRET_KEY
